# DEFAULT

default_config:

api:

# COMPONENTS
sensor: !include components/sensor.yaml
binary_sensor: !include components/binary_sensor.yaml
proximity: !include components/proximity.yaml
template: !include components/template.yaml
camera: !include components/camera.yaml
media_player: !include components/media_player.yaml
switch: !include components/switch.yaml
xiaomi_miot: !include components/xiaomi_miot.yaml
wake_on_lan:

# MISC
http: !include misc/http.yaml
recorder: !include misc/recorder.yaml
influxdb: !include misc/influxdb.yaml

# AUTOMATIONS
automation: !include automations.yaml

# SCRIPTS
script: !include scripts.yaml
