# DEFAULT

default_config:

api:

# COMPONENTS
sensor: !include components/sensor.yaml
binary_sensor: !include components/binary_sensor.yaml
proximity: !include components/proximity.yaml
template: !include components/template.yaml

# MISC
http: !include misc/http.yaml
recorder: !include misc/recorder.yaml
    
# AUTOMATIONS
automation: !include automations.yaml

# SCRIPTS
script: !include scripts.yaml

frontend:
  themes: !include_dir_merge_named themes
